platform: 10.11.92.33

workspace:
  base: /go
  path: src/github.com/theupdateframework/notary

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    pull: true
    dns: 223.5.5.5

pipeline:
  migrate:
    image: registry.cn-qingdao.aliyuncs.com/wod/migrate:v4.14.1
    dns: 223.5.5.5
    commands:
      - mkdir -p dist
      - mv /usr/local/bin/migrate dist/migrate-linux-amd64

  migrate-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/migrate:v4.14.1-arm64
    dns: 223.5.5.5
    commands:
      - mkdir -p dist
      - mv /usr/local/bin/migrate dist/migrate-linux-arm64

  migrate-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/migrate:v4.14.1-ppc64le
    dns: 223.5.5.5
    commands:
      - mkdir -p dist
      - mv /usr/local/bin/migrate dist/migrate-linux-ppc64le

  signer-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.16.5-buster
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    binary: notary-signer
    main: cmd/notary-signer

  signer-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim
    dockerfile: .beagle/signer.dockerfile
    repo: wod/harbor-notary-signer
    version: 'v2.1.5'
    args: 'TARGETOS=linux,TARGETARCH=amd64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  signer-docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-arm64
    dockerfile: .beagle/signer.dockerfile
    repo: wod/harbor-notary-signer
    version: 'v2.1.5'
    channel: arm64
    args: 'TARGETOS=linux,TARGETARCH=arm64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  signer-docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-ppc64le
    dockerfile: .beagle/signer.dockerfile
    repo: wod/harbor-notary-signer
    version: 'v2.1.5'
    channel: ppc64le
    args: 'TARGETOS=linux,TARGETARCH=ppc64le'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  server-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.16.5-buster
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    binary: notary-server
    main: cmd/notary-server

  server-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim
    dockerfile: .beagle/server.dockerfile
    repo: wod/harbor-notary-server
    version: 'v2.1.5'
    args: 'TARGETOS=linux,TARGETARCH=amd64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  server-docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-arm64
    dockerfile: .beagle/server.dockerfile
    repo: wod/harbor-notary-server
    version: 'v2.1.5'
    channel: arm64
    args: 'TARGETOS=linux,TARGETARCH=arm64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  server-docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-ppc64le
    dockerfile: .beagle/server.dockerfile
    repo: wod/harbor-notary-server
    version: 'v2.1.5'
    channel: ppc64le
    args: 'TARGETOS=linux,TARGETARCH=ppc64le'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
