platform: 172.16.0.120

workspace:
  path: src/github.com/theupdateframework/notary

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git-arm64:1.0
    pull: true
    dns: 223.5.5.5

pipeline:

  signer-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arm64:1.14.4-stretch
    pull: true
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/pkg:/go/pkg
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - GOPATH=/go:/drone
    commands:
      - env | grep GO
      - mkdir -p dist
      - apk add --update git gcc libc-dev
      - go get -tags 'mysql postgres file' github.com/mattes/migrate/cli
      - mv /go/bin/cli dist/migrate
      - go install -tags pkcs11 -ldflags "-w -X github.com/theupdateframework/notary/version.GitCommit=`git rev-parse --short HEAD` -X github.com/theupdateframework/notary/version.NotaryVersion=`cat NOTARY_VERSION`" github.com/theupdateframework/notary/cmd/notary-signer
      - mv /drone/bin/notary-signer dist/notary-signer

  signer-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-arm64:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine-arm64:3.9
    dockerfile: .beagle/signer.dockerfile
    repo: wod/awecloud-notary-signer-arm64
    version: "v0.6.1"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  signer-harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-harbor-arm64:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: wod/awecloud-harbor-notary-signer-arm64
    tag: "v1.8.6"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  server-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arm64:1.14.4-stretch
    pull: true
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/pkg:/go/pkg
    environment:
      - GOPROXY=https://goproxy.cn,direct  
      - GOPATH=/go:/drone
    commands:
      - env | grep GO
      - mkdir -p dist    
      - apk add --update git gcc libc-dev
      - go get -tags 'mysql postgres file' github.com/mattes/migrate/cli
      - mv /go/bin/cli dist/migrate
      - go install -tags pkcs11 -ldflags "-w -X github.com/theupdateframework/notary/version.GitCommit=`git rev-parse --short HEAD` -X github.com/theupdateframework/notary/version.NotaryVersion=`cat NOTARY_VERSION`" github.com/theupdateframework/notary/cmd/notary-server
      - mv /drone/bin/notary-server dist/notary-server

  server-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-arm64:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine-arm64:3.9
    dockerfile: .beagle/server.dockerfile
    repo: wod/awecloud-notary-server-arm64
    version: "v0.6.1"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  server-harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-harbor-arm64:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: wod/awecloud-harbor-notary-server-arm64
    tag: "v1.8.6"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD           